runtime : java11
instance_class: F2
env_variables: 
  SPRING_PROFILES_ACTIVE : "prod"
entrypoint: java -noverify -jar demo-0.0.1-SNAPSHOT.jar
spring:
    cloud:
        gcp:
            project-id: Juemily
            sql:
                database-name: crud
                instance-connection-name: juemily:us-central1:morrigan2
    datasource:
        password: M0rr1g4N
        username: morrigan